(glfw:def-key-callback quit-on-escape (window key scancode action mod-keys)
  (declare (ignore window scancode mod-keys))
  (when (and (eq key :escape) (eq action :press))
    (glfw:set-window-should-close)))

(glfw:def-window-size-callback update-viewport (window w h)
  (declare (ignore window))
  (mariko:set-viewport w h))

(defun show-map (path)
  (gl:clear :color-buffer-bit)
  (mariko:map-tile-right-horizontal path 3 65)
  (mariko:map-tile-right-horizontal path 4  65 :xshift 35 :yshift 50)
  (mariko:map-tile-down-vertical path 2 50 :xshift 135 :yshift 50))

(defun main ()
  (sdl2-image:init '(:png))
  (glfw:with-init-window (:title "Test Window" :width 800 :height 400)
    (let ((path "tileGrass.png")) 
      (mariko:load-texture path)
	(glfw:set-window-size-callback 'update-viewport)
	(glfw:set-key-callback 'quit-on-escape)
	(mariko:set-viewport 800 400)
	(gl:clear-color 1 1 1 1)
	(gl:clear :color-buffer)
	(loop until (glfw:window-should-close-p)
	   do (show-map path)
	   do (glfw:poll-events)
	   do (glfw:swap-buffers))))))
